version: 2
updates:
- package-ecosystem: npm
  directory: "/project-a"
  schedule:
    interval: daily
    time: "17:15"
    timezone: "America/New_York"
  versioning-strategy: auto
- package-ecosystem: npm
  directory: "/project-b"
  schedule:
    interval: daily
    time: "17:15"
    timezone: "America/New_York"
  versioning-strategy: auto  